extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:vue/vue3-strongly-recommended'
  - '@vue/typescript/recommended'
  - 'plugin:import/typescript'
parser: vue-eslint-parser
parserOptions:
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions: ['.vue']
  parser: '@typescript-eslint/parser'
plugins:
  - prettier
  - '@typescript-eslint'
  - 'simple-import-sort'
  - 'import'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: false
  semi:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankLine: always
      prev: '*'
      next: return
  prettier/prettier:
    - error
  '@typescript-eslint/explicit-member-accessibility':
    - error
  '@typescript-eslint/prefer-readonly':
    - error
  '@typescript-eslint/strict-boolean-expressions':
    - error
    - allowString: false
      allowNumber: false
      allowNullableObject: false
  no-constant-condition:
    - error
    - checkLoops: false
  simple-import-sort/imports: 'error'
  simple-import-sort/exports: 'error'
  import/newline-after-import: 'error'
